version: '3.8'
services:
  thread:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=forum_docker

  sender:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=forum_docker

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum_docker
    ports:
      - "3306:3306"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:
