version: '3.8'
services:
  thread:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: forum_docker
      ROLE: thread

  sender:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PORT: 8080
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: forum_docker
      ROLE: sender

  db:
    image: mysql:5.7 # Utilisation d'une version spécifique pour plus de stabilité
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum_docker
    ports:
      - "3307:3306" # Port externe modifié pour éviter les conflits, mappé au port interne standard de MySQL
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
      - db-data:/var/lib/mysql

volumes:
  db-data:
