version: '3.8'
services:
  thread:
    image: domeport/thread:latest 
    ports:
      - "81:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: forum_docker

  sender:
    image: domeport/sender:latest 
    ports:
      - "8081:3000"
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: forum_docker

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: forum_docker
    volumes:
      - db-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d


volumes:
  db-data:
